In [2]:
from glob import glob

file_list = glob("/home/vitpc/dev_ws/eda/project/data/each_accident/*")
file_list

['/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (7).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (23).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (41).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (53).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (96).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (80).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (1).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (5).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (46).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (87).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T162932.144.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (43).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (38).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (20).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T162855.870.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (90).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (51).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (32).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (60).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (56).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (66).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (29).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (12).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (37).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (98).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (67).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (10).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T162928.374.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (48).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (21).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T163025.192.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (44).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (55).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T162850.794.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (61).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (14).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (88).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T162937.108.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (25).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (91).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (49).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (6).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T163058.664.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T162900.967.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (75).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (33).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (100).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (57).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T162909.913.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T162904.964.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (50).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (11).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (17).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T162918.934.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T163105.194.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (3).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (64).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (13).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (84).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (69).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (39).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (78).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (63).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (52).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (24).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (54).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (73).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (18).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (70).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (72).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (71).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (8).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T162841.335.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (4).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (62).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T163110.468.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (74).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (59).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (93).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (19).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (83).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (42).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (89).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (97).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T162846.382.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (15).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (95).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (77).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (47).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (92).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (85).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (76).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (2).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (86).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T163019.306.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (99).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (16).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T163037.651.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (65).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (22).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T162914.554.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (81).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (31).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T162835.999.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (9).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (40).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (68).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T163031.817.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (28).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (35).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (27).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (94).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (79).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (45).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T162923.972.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (34).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T163117.659.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T163051.182.xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (36).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (26).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (82).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (30).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 (58).xlsx',
 '/home/vitpc/dev_ws/eda/project/data/each_accident/사고분석-지역별 - 2024-12-30T163044.599.xlsx']

In [3]:
len(file_list)

125

In [4]:
import pandas as pd
data = pd.read_excel(file_list[0])
data.head(2)

,사고번호,발생년월,요일,시군구,사고내용,사망자수,중상자수,경상자수,부상신고자수,사고유형,...,기상상태,도로형태,가해운전자 차종,가해운전자 성별,가해운전자 연령대,가해운전자 상해정도,피해운전자 차종,피해운전자 성별,피해운전자 연령대,피해운전자 상해정도
0,2023010100100239,2023년 1월,일요일,서울특별시 금천구 시흥동,중상사고,0,2,3,0,차대차 - 기타,...,맑음,교차로 - 교차로횡단보도내,승용,여,51-60세,경상,승용,남,41-50세,경상
1,2023010100100284,2023년 1월,일요일,서울특별시 금천구 가산동,경상사고,0,0,2,0,차대차 - 기타,...,맑음,단일로 - 기타,승합,남,51-60세,상해없음,승용,남,31-40세,경상

In [5]:
data_list = []

for file in file_list:
    data = pd.read_excel(file)
    data_list.append(data)

accident_data = pd.concat(data_list)
len(accident_data)

175907

In [6]:
accident_data.head()

,사고번호,발생년월,요일,시군구,사고내용,사망자수,중상자수,경상자수,부상신고자수,사고유형,...,기상상태,도로형태,가해운전자 차종,가해운전자 성별,가해운전자 연령대,가해운전자 상해정도,피해운전자 차종,피해운전자 성별,피해운전자 연령대,피해운전자 상해정도
0,2023010100100239,2023년 1월,일요일,서울특별시 금천구 시흥동,중상사고,0,2,3,0,차대차 - 기타,...,맑음,교차로 - 교차로횡단보도내,승용,여,51-60세,경상,승용,남,41-50세,경상
1,2023010100100284,2023년 1월,일요일,서울특별시 금천구 가산동,경상사고,0,0,2,0,차대차 - 기타,...,맑음,단일로 - 기타,승합,남,51-60세,상해없음,승용,남,31-40세,경상
2,2023010200100075,2023년 1월,월요일,서울특별시 금천구 시흥동,경상사고,0,0,1,0,차대차 - 기타,...,맑음,교차로 - 교차로안,승합,남,41-50세,상해없음,승용,남,65세 이상,경상
3,2023010300100414,2023년 1월,화요일,서울특별시 금천구 시흥동,경상사고,0,0,1,0,차량단독 - 기타,...,맑음,단일로 - 기타,승합,남,61-64세,상해없음,NaN,NaN,NaN,NaN
4,2023010300100444,2023년 1월,화요일,서울특별시 금천구 시흥동,경상사고,0,0,1,0,차대차 - 기타,...,맑음,교차로 - 교차로안,승용,남,31-40세,기타불명,이륜,남,41-50세,경상

In [7]:
accident_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 175907 entries, 0 to 2438
Data columns (total 22 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   사고번호        175907 non-null  int64
 1   발생년월        175907 non-null  object
 2   요일          175907 non-null  object
 3   시군구         175907 non-null  object
 4   사고내용        175907 non-null  object
 5   사망자수        175907 non-null  int64
 6   중상자수        175907 non-null  int64
 7   경상자수        175907 non-null  int64
 8   부상신고자수      175907 non-null  int64
 9   사고유형        175907 non-null  object
 10  법규위반        175907 non-null  object
 11  노면상태        175907 non-null  object
 12  기상상태        175907 non-null  object
 13  도로형태        175907 non-null  object
 14  가해운전자 차종    175907 non-null  object
 15  가해운전자 성별    175907 non-null  object
 16  가해운전자 연령대   175907 non-null  object
 17  가해운전자 상해정도  175907 non-null  object
 18  피해운전자 차종    170722 non-null  object
 19  피해운전자 성별    170722 non-null  object
 20  피해운전자 연령대   170722 non-null  object
 21  피해운전자 상해정도  170722 non-null  object
dtypes: int64(5), object(17)
memory usage: 30.9+ MB

In [8]:
accident_data["도로형태"].unique()

array(['교차로 - 교차로횡단보도내', '단일로 - 기타', '교차로 - 교차로안', '단일로 - 교량',
       '교차로 - 교차로부근', '기타 - 기타', '단일로 - 고가도로위', '단일로 - 터널',
       '단일로 - 지하차도(도로)내', '주차장 - 주차장', '미분류 - 미분류'], dtype=object)

In [9]:
accident_data['도로형태'].value_counts()

도로형태
단일로 - 기타           84850
교차로 - 교차로안         41663
교차로 - 교차로부근        25525
기타 - 기타            12241
교차로 - 교차로횡단보도내      6656
단일로 - 교량            1509
단일로 - 지하차도(도로)내     1256
단일로 - 고가도로위          801
주차장 - 주차장            675
단일로 - 터널             623
미분류 - 미분류            108
Name: count, dtype: int64

In [10]:
accident_data["법규위반"].unique()

array(['안전운전불이행', '안전거리미확보', '기타', '중앙선침범', '신호위반', '보행자보호의무위반', '불법유턴',
       '직진우회전진행방해', '교차로운행방법위반', '차로위반', '과속'], dtype=object)

In [11]:
accident_data['법규위반'].value_counts()

법규위반
안전운전불이행      99655
안전거리미확보      24703
신호위반         20667
기타            6986
보행자보호의무위반     6256
교차로운행방법위반     5817
중앙선침범         4400
직진우회전진행방해     3251
차로위반          2673
불법유턴          1295
과속             204
Name: count, dtype: int64

In [12]:
accident_data["기상상태"].unique()

array(['맑음', '비', '흐림', '기타', '눈', '안개'], dtype=object)

In [13]:
accident_data['기상상태'].value_counts()

기상상태
맑음    155080
비      10697
흐림      6530
기타      3048
눈        540
안개        12
Name: count, dtype: int64

In [14]:
accident_data["노면상태"].unique()

array(['건조', '젖음/습기', '서리/결빙', '기타', '적설', '해빙', '침수'], dtype=object)

In [15]:
accident_data['노면상태'].value_counts()

노면상태
건조       158074
젖음/습기     14076
기타         3037
서리/결빙       450
적설          239
침수           20
해빙           11
Name: count, dtype: int64

In [16]:
accident_data.to_csv("/home/vitpc/dev_ws/eda/project/data/each_accident.csv",sep=",",encoding="euc-kr")

In [17]:
accident_data.head()

,사고번호,발생년월,요일,시군구,사고내용,사망자수,중상자수,경상자수,부상신고자수,사고유형,...,기상상태,도로형태,가해운전자 차종,가해운전자 성별,가해운전자 연령대,가해운전자 상해정도,피해운전자 차종,피해운전자 성별,피해운전자 연령대,피해운전자 상해정도
0,2023010100100239,2023년 1월,일요일,서울특별시 금천구 시흥동,중상사고,0,2,3,0,차대차 - 기타,...,맑음,교차로 - 교차로횡단보도내,승용,여,51-60세,경상,승용,남,41-50세,경상
1,2023010100100284,2023년 1월,일요일,서울특별시 금천구 가산동,경상사고,0,0,2,0,차대차 - 기타,...,맑음,단일로 - 기타,승합,남,51-60세,상해없음,승용,남,31-40세,경상
2,2023010200100075,2023년 1월,월요일,서울특별시 금천구 시흥동,경상사고,0,0,1,0,차대차 - 기타,...,맑음,교차로 - 교차로안,승합,남,41-50세,상해없음,승용,남,65세 이상,경상
3,2023010300100414,2023년 1월,화요일,서울특별시 금천구 시흥동,경상사고,0,0,1,0,차량단독 - 기타,...,맑음,단일로 - 기타,승합,남,61-64세,상해없음,NaN,NaN,NaN,NaN
4,2023010300100444,2023년 1월,화요일,서울특별시 금천구 시흥동,경상사고,0,0,1,0,차대차 - 기타,...,맑음,교차로 - 교차로안,승용,남,31-40세,기타불명,이륜,남,41-50세,경상

In [18]:
sample = accident_data.loc[:,['발생년월','가해운전자 연령대','가해운전자 성별','법규위반','노면상태','기상상태','도로형태']]
sample.head()

       발생년월 가해운전자 연령대 가해운전자 성별     법규위반 노면상태 기상상태            도로형태
0  2023년 1월    51-60세        여  안전운전불이행   건조   맑음  교차로 - 교차로횡단보도내
1  2023년 1월    51-60세        남  안전거리미확보   건조   맑음        단일로 - 기타
2  2023년 1월    41-50세        남  안전운전불이행   건조   맑음      교차로 - 교차로안
3  2023년 1월    61-64세        남       기타   건조   맑음        단일로 - 기타
4  2023년 1월    31-40세        남  안전운전불이행   건조   맑음      교차로 - 교차로안

In [19]:
sample.dropna(inplace=True)

In [20]:
sample.info()

<class 'pandas.core.frame.DataFrame'>
Index: 175907 entries, 0 to 2438
Data columns (total 7 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   발생년월       175907 non-null  object
 1   가해운전자 연령대  175907 non-null  object
 2   가해운전자 성별   175907 non-null  object
 3   법규위반       175907 non-null  object
 4   노면상태       175907 non-null  object
 5   기상상태       175907 non-null  object
 6   도로형태       175907 non-null  object
dtypes: object(7)
memory usage: 10.7+ MB

In [21]:
import pandas as pd

# 기존 파일 읽기

기존_데이터 = pd.read_csv("/home/vitpc/dev_ws/eda/project/data/each_accident.csv",encoding="euc-kr")

# 새로운 파일 읽기

새로운_데이터 = pd.read_csv("/home/vitpc/dev_ws/eda/project/data/drunk driving_accident.csv",encoding="euc-kr")

# 사고번호를 기준으로 겹치는 데이터 찾기 (inner join)
겹치는_데이터 = pd.merge(기존_데이터, 새로운_데이터, on="사고번호", how="inner")

# 기존 데이터에서 사고번호가 겹치는 데이터의 법규위반 값을 모두 '음주'로 변경
기존_데이터.loc[기존_데이터["사고번호"].isin(겹치는_데이터["사고번호"]), "법규위반"] = "음주"

# 변경된 데이터 확인
기존_데이터.head()

,Unnamed: 0,사고번호,발생년월,요일,시군구,사고내용,사망자수,중상자수,경상자수,부상신고자수,...,기상상태,도로형태,가해운전자 차종,가해운전자 성별,가해운전자 연령대,가해운전자 상해정도,피해운전자 차종,피해운전자 성별,피해운전자 연령대,피해운전자 상해정도
0,0,2023010100100239,2023년 1월,일요일,서울특별시 금천구 시흥동,중상사고,0,2,3,0,...,맑음,교차로 - 교차로횡단보도내,승용,여,51-60세,경상,승용,남,41-50세,경상
1,1,2023010100100284,2023년 1월,일요일,서울특별시 금천구 가산동,경상사고,0,0,2,0,...,맑음,단일로 - 기타,승합,남,51-60세,상해없음,승용,남,31-40세,경상
2,2,2023010200100075,2023년 1월,월요일,서울특별시 금천구 시흥동,경상사고,0,0,1,0,...,맑음,교차로 - 교차로안,승합,남,41-50세,상해없음,승용,남,65세 이상,경상
3,3,2023010300100414,2023년 1월,화요일,서울특별시 금천구 시흥동,경상사고,0,0,1,0,...,맑음,단일로 - 기타,승합,남,61-64세,상해없음,NaN,NaN,NaN,NaN
4,4,2023010300100444,2023년 1월,화요일,서울특별시 금천구 시흥동,경상사고,0,0,1,0,...,맑음,교차로 - 교차로안,승용,남,31-40세,기타불명,이륜,남,41-50세,경상

In [22]:
기존_데이터.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175907 entries, 0 to 175906
Data columns (total 23 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  175907 non-null  int64
 1   사고번호        175907 non-null  int64
 2   발생년월        175907 non-null  object
 3   요일          175907 non-null  object
 4   시군구         175907 non-null  object
 5   사고내용        175907 non-null  object
 6   사망자수        175907 non-null  int64
 7   중상자수        175907 non-null  int64
 8   경상자수        175907 non-null  int64
 9   부상신고자수      175907 non-null  int64
 10  사고유형        175907 non-null  object
 11  법규위반        175907 non-null  object
 12  노면상태        175907 non-null  object
 13  기상상태        175907 non-null  object
 14  도로형태        175907 non-null  object
 15  가해운전자 차종    175907 non-null  object
 16  가해운전자 성별    175907 non-null  object
 17  가해운전자 연령대   175907 non-null  object
 18  가해운전자 상해정도  175907 non-null  object
 19  피해운전자 차종    170722 non-null  object
 20  피해운전자 성별    170722 non-null  object
 21  피해운전자 연령대   170722 non-null  object
 22  피해운전자 상해정도  170722 non-null  object
dtypes: int64(6), object(17)
memory usage: 30.9+ MB

In [23]:
기존_데이터["법규위반"].unique()

array(['안전운전불이행', '안전거리미확보', '기타', '음주', '신호위반', '보행자보호의무위반', '중앙선침범',
       '불법유턴', '직진우회전진행방해', '교차로운행방법위반', '차로위반', '과속'], dtype=object)

In [24]:
기존_데이터["법규위반"].value_counts()

법규위반
안전운전불이행      91393
안전거리미확보      23978
신호위반         19832
음주           10862
기타            6718
보행자보호의무위반     6196
교차로운행방법위반     5746
중앙선침범         3907
직진우회전진행방해     3218
차로위반          2619
불법유턴          1260
과속             178
Name: count, dtype: int64

In [44]:
# 변경된 데이터를 새로운 파일로 저장
기존_데이터.to_csv("/home/vitpc/dev_ws/eda/project/data/total_accident.csv", index=False)

In [45]:
efficient_data = 기존_데이터.loc[:,['발생년월','가해운전자 연령대','가해운전자 성별','법규위반','노면상태','기상상태','도로형태']]
efficient_data.head()

       발생년월 가해운전자 연령대 가해운전자 성별     법규위반 노면상태 기상상태            도로형태
0  2023년 1월    51-60세        여  안전운전불이행   건조   맑음  교차로 - 교차로횡단보도내
1  2023년 1월    51-60세        남  안전거리미확보   건조   맑음        단일로 - 기타
2  2023년 1월    41-50세        남  안전운전불이행   건조   맑음      교차로 - 교차로안
3  2023년 1월    61-64세        남       기타   건조   맑음        단일로 - 기타
4  2023년 1월    31-40세        남  안전운전불이행   건조   맑음      교차로 - 교차로안

In [46]:
len(efficient_data)

175907

In [47]:
efficient_data["법규위반"].value_counts()

법규위반
안전운전불이행      91393
안전거리미확보      23978
신호위반         19832
음주           10862
기타            6718
보행자보호의무위반     6196
교차로운행방법위반     5746
중앙선침범         3907
직진우회전진행방해     3218
차로위반          2619
불법유턴          1260
과속             178
Name: count, dtype: int64

In [48]:
efficient_data["노면상태"].value_counts()

노면상태
건조       158074
젖음/습기     14076
기타         3037
서리/결빙       450
적설          239
침수           20
해빙           11
Name: count, dtype: int64

In [49]:
efficient_data["기상상태"].value_counts()

기상상태
맑음    155080
비      10697
흐림      6530
기타      3048
눈        540
안개        12
Name: count, dtype: int64

In [50]:
efficient_data["도로형태"].value_counts()

도로형태
단일로 - 기타           84850
교차로 - 교차로안         41663
교차로 - 교차로부근        25525
기타 - 기타            12241
교차로 - 교차로횡단보도내      6656
단일로 - 교량            1509
단일로 - 지하차도(도로)내     1256
단일로 - 고가도로위          801
주차장 - 주차장            675
단일로 - 터널             623
미분류 - 미분류            108
Name: count, dtype: int64

In [51]:
efficient_data = 기존_데이터.loc[:,['발생년월','가해운전자 연령대','가해운전자 성별','법규위반','노면상태','기상상태','도로형태']]
efficient_data.head()

       발생년월 가해운전자 연령대 가해운전자 성별     법규위반 노면상태 기상상태            도로형태
0  2023년 1월    51-60세        여  안전운전불이행   건조   맑음  교차로 - 교차로횡단보도내
1  2023년 1월    51-60세        남  안전거리미확보   건조   맑음        단일로 - 기타
2  2023년 1월    41-50세        남  안전운전불이행   건조   맑음      교차로 - 교차로안
3  2023년 1월    61-64세        남       기타   건조   맑음        단일로 - 기타
4  2023년 1월    31-40세        남  안전운전불이행   건조   맑음      교차로 - 교차로안

In [52]:
# 매핑 기준 정의
pavement_mapping = {
    '건조': 0,
    '젖음/습기': 1,
    '서리/결빙': 2,
    '적설': 2,
    '해빙': 2,
    '기타': 3,
    '침수': 3
}

# '노면상태' 컬럼의 값을 매핑
efficient_data['노면상태'] = efficient_data['노면상태'].map(pavement_mapping)

# 결과 확인
efficient_data.tail(10)

             발생년월 가해운전자 연령대 가해운전자 성별       법규위반  노면상태 기상상태            도로형태
175897  2019년 12월    51-60세        남    안전운전불이행     1    비        단일로 - 기타
175898  2019년 12월    51-60세        남    안전거리미확보     0   맑음      교차로 - 교차로안
175899  2019년 12월    51-60세        남    안전운전불이행     0   맑음      교차로 - 교차로안
175900  2019년 12월    31-40세        남    안전운전불이행     0   맑음     교차로 - 교차로부근
175901  2019년 12월    65세 이상        남  보행자보호의무위반     0   맑음  교차로 - 교차로횡단보도내
175902  2019년 12월    65세 이상        남  보행자보호의무위반     0   맑음  교차로 - 교차로횡단보도내
175903  2019년 12월    41-50세        남         음주     0   맑음     교차로 - 교차로부근
175904  2019년 12월    65세 이상        남    안전거리미확보     0   맑음        단일로 - 기타
175905  2019년 12월    51-60세        남    안전운전불이행     0   맑음      교차로 - 교차로안
175906  2019년 12월    20세 이하        남         음주     0   맑음         기타 - 기타

In [53]:
# 매핑 기준 정의
weather_mapping = {
    '맑음': 0,
    '흐림': 1,
    '안개': 1,
    '비': 2,
    '눈': 3,
    '기타': 4
}

# '기상상태' 컬럼의 값을 매핑
efficient_data['기상상태'] = efficient_data['기상상태'].map(weather_mapping)

# 결과 확인
efficient_data.tail(10)

             발생년월 가해운전자 연령대 가해운전자 성별       법규위반  노면상태  기상상태            도로형태
175897  2019년 12월    51-60세        남    안전운전불이행     1     2        단일로 - 기타
175898  2019년 12월    51-60세        남    안전거리미확보     0     0      교차로 - 교차로안
175899  2019년 12월    51-60세        남    안전운전불이행     0     0      교차로 - 교차로안
175900  2019년 12월    31-40세        남    안전운전불이행     0     0     교차로 - 교차로부근
175901  2019년 12월    65세 이상        남  보행자보호의무위반     0     0  교차로 - 교차로횡단보도내
175902  2019년 12월    65세 이상        남  보행자보호의무위반     0     0  교차로 - 교차로횡단보도내
175903  2019년 12월    41-50세        남         음주     0     0     교차로 - 교차로부근
175904  2019년 12월    65세 이상        남    안전거리미확보     0     0        단일로 - 기타
175905  2019년 12월    51-60세        남    안전운전불이행     0     0      교차로 - 교차로안
175906  2019년 12월    20세 이하        남         음주     0     0         기타 - 기타

In [54]:
# 매핑 기준 정의
road_type_mapping = {
    '단일로 - 교량': 0,
    '단일로 - 지하차도(도로)내': 0,
    '단일로 - 고가도로위': 0,
    '단일로 - 터널': 0,
    '단일로 - 기타': 1,
    '교차로 - 교차로안': 2,
    '교차로 - 교차로부근': 2,
    '교차로 - 교차로횡단보도내': 2,
    '주차장 - 주차장': 3,
    '기타 - 기타': 4,
    '미분류 - 미분류': 4
}

# '도로형태' 컬럼의 값을 매핑
efficient_data['도로형태'] = efficient_data['도로형태'].map(road_type_mapping)

# 결과 확인
efficient_data.tail(10)

             발생년월 가해운전자 연령대 가해운전자 성별       법규위반  노면상태  기상상태  도로형태
175897  2019년 12월    51-60세        남    안전운전불이행     1     2     1
175898  2019년 12월    51-60세        남    안전거리미확보     0     0     2
175899  2019년 12월    51-60세        남    안전운전불이행     0     0     2
175900  2019년 12월    31-40세        남    안전운전불이행     0     0     2
175901  2019년 12월    65세 이상        남  보행자보호의무위반     0     0     2
175902  2019년 12월    65세 이상        남  보행자보호의무위반     0     0     2
175903  2019년 12월    41-50세        남         음주     0     0     2
175904  2019년 12월    65세 이상        남    안전거리미확보     0     0     1
175905  2019년 12월    51-60세        남    안전운전불이행     0     0     2
175906  2019년 12월    20세 이하        남         음주     0     0     4

In [55]:
# NaN 값 확인
print(efficient_data[efficient_data['도로형태'].isna()])

Empty DataFrame
Columns: [발생년월, 가해운전자 연령대, 가해운전자 성별, 법규위반, 노면상태, 기상상태, 도로형태]
Index: []

In [56]:
# 매핑 기준 정의
violation_mapping = {
    '중앙선침범': 0,
    '차로위반': 1,
    '교차로운행방법위반': 1,
    '과속': 2,
    '안전거리미확보': 2,
    '직진우회전진행방해': 3,
    '불법유턴': 4,
    '음주': 6,
    '기타': 8,
    '보행자보호의무위반': 8,
    '안전운전불이행': 8,
    '신호위반': 9
}

# '법규위반' 컬럼 매핑
efficient_data['법규위반'] = efficient_data['법규위반'].map(violation_mapping)

# 결과 확인
efficient_data.tail(10)

             발생년월 가해운전자 연령대 가해운전자 성별  법규위반  노면상태  기상상태  도로형태
175897  2019년 12월    51-60세        남     8     1     2     1
175898  2019년 12월    51-60세        남     2     0     0     2
175899  2019년 12월    51-60세        남     8     0     0     2
175900  2019년 12월    31-40세        남     8     0     0     2
175901  2019년 12월    65세 이상        남     8     0     0     2
175902  2019년 12월    65세 이상        남     8     0     0     2
175903  2019년 12월    41-50세        남     6     0     0     2
175904  2019년 12월    65세 이상        남     2     0     0     1
175905  2019년 12월    51-60세        남     8     0     0     2
175906  2019년 12월    20세 이하        남     6     0     0     4

In [57]:
efficient_data["가해운전자 연령대"].value_counts()

가해운전자 연령대
51-60세    38939
41-50세    30152
65세 이상    29450
31-40세    28366
21-30세    23277
61-64세    16235
20세 이하     5602
기타불명       3886
Name: count, dtype: int64

In [58]:
# 매핑 기준 정의
age_mapping = {
    '65세 이상': 65,
    '61-64세':62,
    '51-60세': 55,
    '41-50세': 45,
    '31-40세': 35,
    '21-30세': 25,
    '20세 이하': 20,
    '기타불명': None
}

# '법규위반' 컬럼 매핑
efficient_data['가해운전자 연령대'] = efficient_data['가해운전자 연령대'].map(age_mapping)

# 결과 확인
efficient_data.tail(10)

             발생년월  가해운전자 연령대 가해운전자 성별  법규위반  노면상태  기상상태  도로형태
175897  2019년 12월       55.0        남     8     1     2     1
175898  2019년 12월       55.0        남     2     0     0     2
175899  2019년 12월       55.0        남     8     0     0     2
175900  2019년 12월       35.0        남     8     0     0     2
175901  2019년 12월       65.0        남     8     0     0     2
175902  2019년 12월       65.0        남     8     0     0     2
175903  2019년 12월       45.0        남     6     0     0     2
175904  2019년 12월       65.0        남     2     0     0     1
175905  2019년 12월       55.0        남     8     0     0     2
175906  2019년 12월       20.0        남     6     0     0     4

In [59]:
# 매핑 기준 정의
sex_mapping = {
    '남': 'M',
    '여': 'F'
}

# '법규위반' 컬럼 매핑
efficient_data['가해운전자 성별'] = efficient_data['가해운전자 성별'].map(sex_mapping)

# 결과 확인
efficient_data.tail(10)

             발생년월  가해운전자 연령대 가해운전자 성별  법규위반  노면상태  기상상태  도로형태
175897  2019년 12월       55.0        M     8     1     2     1
175898  2019년 12월       55.0        M     2     0     0     2
175899  2019년 12월       55.0        M     8     0     0     2
175900  2019년 12월       35.0        M     8     0     0     2
175901  2019년 12월       65.0        M     8     0     0     2
175902  2019년 12월       65.0        M     8     0     0     2
175903  2019년 12월       45.0        M     6     0     0     2
175904  2019년 12월       65.0        M     2     0     0     1
175905  2019년 12월       55.0        M     8     0     0     2
175906  2019년 12월       20.0        M     6     0     0     4

In [60]:
# 새로운 컬럼 추가 및 값 할당
efficient_data['state'] = 0  # 'state' 컬럼에 0 추가
efficient_data['speed'] = None  # 'speed' 컬럼에 null 값 추가
efficient_data['brand'] = None  # 'brand' 컬럼에 null 값 추가
efficient_data['auto'] = 1  # 'auto' 컬럼에 1 추가

# 결과 확인
efficient_data.head()

,발생년월,가해운전자 연령대,가해운전자 성별,법규위반,노면상태,기상상태,도로형태,state,speed,brand,auto
0,2023년 1월,55.0,F,8,0,0,2,0,None,None,1
1,2023년 1월,55.0,M,2,0,0,1,0,None,None,1
2,2023년 1월,45.0,M,8,0,0,2,0,None,None,1
3,2023년 1월,62.0,M,8,0,0,1,0,None,None,1
4,2023년 1월,35.0,M,8,0,0,2,0,None,None,1

In [61]:
efficient_data.to_csv("/home/vitpc/dev_ws/eda/project/data/final_data.csv", encoding='euc-kr')

In [62]:
df = pd.read_csv("/home/vitpc/dev_ws/eda/project/data/final_data.csv", encoding='euc-kr')
df.head()

,Unnamed: 0,발생년월,가해운전자 연령대,가해운전자 성별,법규위반,노면상태,기상상태,도로형태,state,speed,brand,auto
0,0,2023년 1월,55.0,F,8,0,0,2,0,NaN,NaN,1
1,1,2023년 1월,55.0,M,2,0,0,1,0,NaN,NaN,1
2,2,2023년 1월,45.0,M,8,0,0,2,0,NaN,NaN,1
3,3,2023년 1월,62.0,M,8,0,0,1,0,NaN,NaN,1
4,4,2023년 1월,35.0,M,8,0,0,2,0,NaN,NaN,1