### USA Autonomous driving data

In [68]:
import pandas as pd

usec = [2, 49, 61, 66, 67, 72, 73, 74, 76, 98, 102]

df_ads = pd.read_csv("../data/ads.csv", usecols = usec)
df_adas = pd.read_csv("../data/adas_level2.csv", usecols = usec)
print(df_ads)

                   Reporting Entity Incident Date             City  \
0                         Waymo LLC      APR-2024  Paradise Valley
1                         Waymo LLC      OCT-2024            Tempe
2                         Waymo LLC      OCT-2024          Phoenix
3                         Waymo LLC      OCT-2024    San Francisco
4                         Waymo LLC      OCT-2024    San Francisco
...                             ...           ...              ...
1593                      Waymo LLC      JUL-2021    San Francisco
1594  Transdev Alternative Services      JUL-2021    San Francisco
1595                      Waymo LLC      JUL-2021    San Francisco
1596  Transdev Alternative Services      JUL-2021    San Francisco
1597                      Waymo LLC      JUL-2021    San Francisco

      Roadway Type Roadway Surface Weather - Clear Weather - Snow  \
0      Parking Lot             Dry               Y
1           Street             Dry               Y
2           Street             Dry               Y
3           Street             Dry
4           Street             Dry               Y
...            ...             ...             ...            ...
1593  Intersection             Dry
1594        Street             Dry               Y
1595        Street             Dry               Y
1596  Intersection             Dry
1597  Intersection             Dry

     Weather - Cloudy Weather - Rain SV Pre-Crash Movement  \
0                                      Proceeding Straight
1                                                  Stopped
2                                                  Stopped
3                   Y                              Stopped
4                                                  Stopped
...               ...            ...                   ...
1593                Y                     Making Left Turn
1594                                   Proceeding Straight
1595                                   Proceeding Straight
1596                Y                     Making Left Turn
1597                Y                     Making Left Turn

      SV Precrash Speed (MPH)
0                         5.0
1                         0.0
2                         0.0
3                         0.0
4                         0.0
...                       ...
1593                      NaN
1594                     18.0
1595                     18.0
1596                      NaN
1597                      NaN

[1598 rows x 11 columns]

In [69]:
# Weather 기본값 설정
df_ads["Weather"] = "Other"

# 조건에 따라 Weather 열 수정
df_ads.loc[df_ads["Weather - Clear"] == 'Y', "Weather"] = "Clear"
df_ads.loc[df_ads["Weather - Snow"] == 'Y', "Weather"] = "Snow"
df_ads.loc[df_ads["Weather - Cloudy"] == 'Y', "Weather"] = "Cloudy"
df_ads.loc[df_ads["Weather - Rain"] == 'Y', "Weather"] = "Rain"

# 불필요한 열 삭제
df_ads = df_ads.drop(columns=["Weather - Clear", "Weather - Snow", "Weather - Cloudy", "Weather - Rain"])

# NaN 행 삭제
df_ads = df_ads.dropna()



# Weather 기본값 설정
df_adas["Weather"] = "Other"

# 조건에 따라 Weather 열 수정
df_adas.loc[df_adas["Weather - Clear"] == 'Y', "Weather"] = "Clear"
df_adas.loc[df_adas["Weather - Snow"] == 'Y', "Weather"] = "Snow"
df_adas.loc[df_adas["Weather - Cloudy"] == 'Y', "Weather"] = "Cloudy"
df_adas.loc[df_adas["Weather - Rain"] == 'Y', "Weather"] = "Rain"

# 불필요한 열 삭제
df_adas = df_adas.drop(columns=["Weather - Clear", "Weather - Snow", "Weather - Cloudy", "Weather - Rain"])
#df_adas.loc[df_adas["ADAS/ADS System Version"] == "[REDACTED, MAY CONTAIN CONFIDENTIAL BUSINESS INFORMATION]", "ADAS/ADS System Version"] = "level 2"

# NaN 행 삭제
df_adas = df_adas.dropna()

In [70]:
df_ads.head(5)

,Reporting Entity,Incident Date,City,Roadway Type,Roadway Surface,SV Pre-Crash Movement,SV Precrash Speed (MPH),Weather
0,Waymo LLC,APR-2024,Paradise Valley,Parking Lot,Dry,Proceeding Straight,5.0,Clear
1,Waymo LLC,OCT-2024,Tempe,Street,Dry,Stopped,0.0,Clear
2,Waymo LLC,OCT-2024,Phoenix,Street,Dry,Stopped,0.0,Clear
3,Waymo LLC,OCT-2024,San Francisco,Street,Dry,Stopped,0.0,Cloudy
4,Waymo LLC,OCT-2024,San Francisco,Street,Dry,Stopped,0.0,Clear

In [71]:
df_adas.head(5)

,Reporting Entity,Incident Date,City,Roadway Type,Roadway Surface,SV Pre-Crash Movement,SV Precrash Speed (MPH),Weather
0,Honda (American Honda Motor Co.),NOV-2024,LOUISVILLE,Street,Dry,Proceeding Straight,60.0,Clear
2,"Nissan North America, Inc.",OCT-2024,Irving,Highway / Freeway,Unknown,Unknown,26.0,Other
3,"Subaru of America, Inc.",NOV-2024,Plainview,Rural Road,Dry,Proceeding Straight,78.0,Clear
5,"Tesla, Inc.",NOV-2024,Worcester,Unknown,Unknown,Unknown,30.0,Other
6,"Tesla, Inc.",NOV-2024,Bothell,Unknown,Unknown,Unknown,12.0,Other

In [72]:
df_ads["Speed"] = df_ads["SV Precrash Speed (MPH)"] * 1.60934
df_ads["Speed"] = df_ads["Speed"].round().astype(int)
df_ads = df_ads.drop(columns=["SV Precrash Speed (MPH)"])

df_ads.rename(columns={"Reporting Entity" : "Brand"}, inplace=True)
df_ads.rename(columns={"ADAS/ADS System Version" : "Level"}, inplace=True)
df_ads.rename(columns={"Incident Date": "Accident date"}, inplace=True)
df_ads.rename(columns={"Roadway Type": "Road"}, inplace=True)
df_ads.rename(columns={"Roadway Surface": "Pavement"}, inplace=True)
df_ads.rename(columns={"SV Pre-Crash Movement": "Movement"}, inplace=True)

df_ads.head(5)

,Brand,Accident date,City,Road,Pavement,Movement,Weather,Speed
0,Waymo LLC,APR-2024,Paradise Valley,Parking Lot,Dry,Proceeding Straight,Clear,8
1,Waymo LLC,OCT-2024,Tempe,Street,Dry,Stopped,Clear,0
2,Waymo LLC,OCT-2024,Phoenix,Street,Dry,Stopped,Clear,0
3,Waymo LLC,OCT-2024,San Francisco,Street,Dry,Stopped,Cloudy,0
4,Waymo LLC,OCT-2024,San Francisco,Street,Dry,Stopped,Clear,0

In [73]:
df_adas["Speed"] = df_adas["SV Precrash Speed (MPH)"] * 1.60934
df_adas["Speed"] = df_adas["Speed"].round().astype(int)
df_adas = df_adas.drop(columns=["SV Precrash Speed (MPH)"])

df_adas.rename(columns={"Reporting Entity" : "Brand"}, inplace=True)
df_adas.rename(columns={"ADAS/ADS System Version" : "Level"}, inplace=True)
df_adas.rename(columns={"Incident Date": "Accident date"}, inplace=True)
df_adas.rename(columns={"Roadway Type": "Road"}, inplace=True)
df_adas.rename(columns={"Roadway Surface": "Pavement"}, inplace=True)
df_adas.rename(columns={"SV Pre-Crash Movement": "Movement"}, inplace=True)

df_adas.head(5)

,Brand,Accident date,City,Road,Pavement,Movement,Weather,Speed
0,Honda (American Honda Motor Co.),NOV-2024,LOUISVILLE,Street,Dry,Proceeding Straight,Clear,97
2,"Nissan North America, Inc.",OCT-2024,Irving,Highway / Freeway,Unknown,Unknown,Other,42
3,"Subaru of America, Inc.",NOV-2024,Plainview,Rural Road,Dry,Proceeding Straight,Clear,126
5,"Tesla, Inc.",NOV-2024,Worcester,Unknown,Unknown,Unknown,Other,48
6,"Tesla, Inc.",NOV-2024,Bothell,Unknown,Unknown,Unknown,Other,19

In [94]:
import mysql.connector

cnt = 1
dic = {"JAN":"01", "FEB":"02", "MAR":"03", "APR":"04", "MAY":"05", "JUN":"06", "JUL":"07", "AUG":"08", "SEP":"09", "OCT":"10", "NOV":"11", "DEC":"12"}

remote = mysql.connector.connect(
    host = "database-eda.chuw4mu887pw.ap-northeast-2.rds.amazonaws.com",
    user = "root",
    password = "myung234",
    database = "eda"
)

cursor = remote.cursor(buffered = True)

sql = """
INSERT INTO car_accident (
    accident_date, alcohol, speed, age, sex, auto_id, state_id, 
    weather_id, road_id, movement_id, brand_id, pavement_id
) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

for i, row in df_ads.iterrows():
    # SF
    if row[2] != "San Francisco": continue

    # brand
    if row[0] == "Waymo LLC": brand = 0
    elif row[0] == "Cruise LLC": brand = 2
    elif row[0] == "Transdev Alternative Services": brand = 3
    elif row[0] == "Zoox, Inc.": brand = 4
    elif row[0] == "Toyota Motor Engineering & Manufacturing": brand = 5
    elif row[0] == "Lucid USA, Inc.": brand = 7
    else: continue

    # speed
    speed = row[7] 

    # weather
    if row[6] == "Clear": weather = 0
    elif row[6] == "Cloudy": weather = 1
    elif row[6] == "Rain": weather = 2
    elif row[6] == "Snow": weather = 3
    elif row[6] == "Other": weather = 4

    # road
    if row[3] == "Street": road = 0
    elif row[3] == "Highway / Freeway": road = 1
    elif row[3] == "Intersection" or row[3] == "Traffic Circle": road = 2
    elif row[3] == "Parking Lot": road = 3
    else: continue

    # movement
    if row[5] == "Crossing into Opposing Lane": movement = 0
    elif row[5] == "Changing Lanes" or row[5] == "Lane / Road Departure" or row[5] == "Entering Traffic" or row[5] == "Merging": movement = 1
    elif row[5] == "Proceeding Straight": movement = 2
    elif row[5] == "Making Left Turn" or row[5] == "Making Right Turn": movement = 3
    elif row[5] == "Making U-Turn": movement = 4
    elif row[5] == "Parking Maneuver" or row[5] == "Parked": movement = 5
    else: movement = 8

    # pavement
    if row[4] == "Dry": pavement = 0
    elif row[4] == "Wet": pavement = 1
    elif row[4] == "Snow / Slush / Ice": pavement = 2
    else: pavement = 3
        
    # date    
    date = ""
    date += row[1][-4:]
    date += dic[row[1][:3]]
    date += "01"

    tmp = (date, None, speed, None, None, 0, 1, weather, road, movement, brand, pavement)
    
    cursor.execute(sql, tmp)
    remote.commit()
    print("complete commit", str(cnt))
    cnt += 1
    
remote.close()

/tmp/ipykernel_3893/3112454515.py:25: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if row[2] != "San Francisco": continue
/tmp/ipykernel_3893/3112454515.py:28: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if row[0] == "Waymo LLC": brand = 0
/tmp/ipykernel_3893/3112454515.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  speed = row[7]
/tmp/ipykernel_3893/3112454515.py:40: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if row[6] == "Clear": weather = 0
/tmp/ipykernel_3893/3112454515.py:41: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[6] == "Cloudy": weather = 1
/tmp/ipykernel_3893/3112454515.py:47: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if row[3] == "Street": road = 0
/tmp/ipykernel_3893/3112454515.py:54: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if row[5] == "Crossing into Opposing Lane": movement = 0
/tmp/ipykernel_3893/3112454515.py:55: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[5] == "Changing Lanes" or row[5] == "Lane / Road Departure" or row[5] == "Entering Traffic" or row[5] == "Merging": movement = 1
/tmp/ipykernel_3893/3112454515.py:56: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[5] == "Proceeding Straight": movement = 2
/tmp/ipykernel_3893/3112454515.py:57: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[5] == "Making Left Turn" or row[5] == "Making Right Turn": movement = 3
/tmp/ipykernel_3893/3112454515.py:58: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[5] == "Making U-Turn": movement = 4
/tmp/ipykernel_3893/3112454515.py:59: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[5] == "Parking Maneuver" or row[5] == "Parked": movement = 5
/tmp/ipykernel_3893/3112454515.py:63: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if row[4] == "Dry": pavement = 0
/tmp/ipykernel_3893/3112454515.py:70: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  date += row[1][-4:]
/tmp/ipykernel_3893/3112454515.py:71: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  date += dic[row[1][:3]]
/tmp/ipykernel_3893/3112454515.py:48: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[3] == "Highway / Freeway": road = 1
/tmp/ipykernel_3893/3112454515.py:49: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[3] == "Intersection" or row[3] == "Traffic Circle": road = 2

complete commit 1
complete commit 2
complete commit 3
complete commit 4
complete commit 5
complete commit 6
complete commit 7
complete commit 8
complete commit 9
complete commit 10
complete commit 11
complete commit 12
complete commit 13
complete commit 14
complete commit 15
complete commit 16
complete commit 17
complete commit 18
complete commit 19
complete commit 20
complete commit 21

/tmp/ipykernel_3893/3112454515.py:29: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[0] == "Cruise LLC": brand = 2
/tmp/ipykernel_3893/3112454515.py:30: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[0] == "Transdev Alternative Services": brand = 3
/tmp/ipykernel_3893/3112454515.py:31: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[0] == "Zoox, Inc.": brand = 4

complete commit 22
complete commit 23
complete commit 24
complete commit 25
complete commit 26
complete commit 27
complete commit 28
complete commit 29
complete commit 30
complete commit 31
complete commit 32
complete commit 33
complete commit 34
complete commit 35
complete commit 36
complete commit 37
complete commit 38
complete commit 39
complete commit 40
complete commit 41
complete commit 42
complete commit 43
complete commit 44
complete commit 45
complete commit 46
complete commit 47
complete commit 48
complete commit 49
complete commit 50
complete commit 51

/tmp/ipykernel_3893/3112454515.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[6] == "Rain": weather = 2
/tmp/ipykernel_3893/3112454515.py:43: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[6] == "Snow": weather = 3
/tmp/ipykernel_3893/3112454515.py:44: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[6] == "Other": weather = 4
/tmp/ipykernel_3893/3112454515.py:50: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[3] == "Parking Lot": road = 3

complete commit 52
complete commit 53
complete commit 54
complete commit 55
complete commit 56
complete commit 57
complete commit 58
complete commit 59
complete commit 60
complete commit 61
complete commit 62
complete commit 63
complete commit 64
complete commit 65
complete commit 66
complete commit 67
complete commit 68
complete commit 69
complete commit 70
complete commit 71
complete commit 72
complete commit 73
complete commit 74
complete commit 75
complete commit 76
complete commit 77
complete commit 78
complete commit 79
complete commit 80
complete commit 81
complete commit 82
complete commit 83
complete commit 84

/tmp/ipykernel_3893/3112454515.py:32: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[0] == "Toyota Motor Engineering & Manufacturing": brand = 5
/tmp/ipykernel_3893/3112454515.py:33: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[0] == "Lucid USA, Inc.": brand = 7

complete commit 85
complete commit 86
complete commit 87
complete commit 88
complete commit 89
complete commit 90
complete commit 91
complete commit 92
complete commit 93
complete commit 94
complete commit 95
complete commit 96
complete commit 97
complete commit 98
complete commit 99
complete commit 100
complete commit 101
complete commit 102
complete commit 103
complete commit 104
complete commit 105
complete commit 106
complete commit 107
complete commit 108
complete commit 109
complete commit 110
complete commit 111
complete commit 112
complete commit 113
complete commit 114
complete commit 115
complete commit 116
complete commit 117
complete commit 118
complete commit 119
complete commit 120
complete commit 121
complete commit 122
complete commit 123
complete commit 124
complete commit 125
complete commit 126
complete commit 127
complete commit 128
complete commit 129
complete commit 130
complete commit 131
complete commit 132
complete commit 133
complete commit 134
complete commit 135
complete commit 136
complete commit 137
complete commit 138
complete commit 139
complete commit 140
complete commit 141
complete commit 142
complete commit 143
complete commit 144
complete commit 145
complete commit 146
complete commit 147
complete commit 148
complete commit 149
complete commit 150
complete commit 151
complete commit 152
complete commit 153
complete commit 154
complete commit 155
complete commit 156
complete commit 157
complete commit 158
complete commit 159
complete commit 160
complete commit 161
complete commit 162
complete commit 163
complete commit 164
complete commit 165
complete commit 166
complete commit 167
complete commit 168
complete commit 169
complete commit 170
complete commit 171
complete commit 172
complete commit 173
complete commit 174
complete commit 175
complete commit 176
complete commit 177
complete commit 178
complete commit 179
complete commit 180
complete commit 181
complete commit 182
complete commit 183
complete commit 184
complete commit 185
complete commit 186
complete commit 187
complete commit 188
complete commit 189
complete commit 190
complete commit 191
complete commit 192
complete commit 193
complete commit 194
complete commit 195
complete commit 196
complete commit 197
complete commit 198
complete commit 199
complete commit 200

/tmp/ipykernel_3893/3112454515.py:64: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[4] == "Wet": pavement = 1

complete commit 201
complete commit 202
complete commit 203
complete commit 204
complete commit 205
complete commit 206
complete commit 207
complete commit 208
complete commit 209
complete commit 210
complete commit 211
complete commit 212
complete commit 213
complete commit 214
complete commit 215
complete commit 216
complete commit 217
complete commit 218
complete commit 219
complete commit 220
complete commit 221
complete commit 222
complete commit 223
complete commit 224
complete commit 225
complete commit 226
complete commit 227
complete commit 228
complete commit 229
complete commit 230
complete commit 231
complete commit 232
complete commit 233
complete commit 234
complete commit 235
complete commit 236
complete commit 237
complete commit 238
complete commit 239
complete commit 240
complete commit 241
complete commit 242
complete commit 243
complete commit 244
complete commit 245
complete commit 246
complete commit 247
complete commit 248
complete commit 249
complete commit 250
complete commit 251
complete commit 252
complete commit 253
complete commit 254
complete commit 255
complete commit 256
complete commit 257
complete commit 258
complete commit 259
complete commit 260
complete commit 261
complete commit 262
complete commit 263
complete commit 264
complete commit 265
complete commit 266
complete commit 267
complete commit 268
complete commit 269
complete commit 270
complete commit 271
complete commit 272
complete commit 273
complete commit 274
complete commit 275
complete commit 276
complete commit 277
complete commit 278
complete commit 279
complete commit 280
complete commit 281
complete commit 282
complete commit 283
complete commit 284
complete commit 285
complete commit 286
complete commit 287
complete commit 288
complete commit 289
complete commit 290
complete commit 291
complete commit 292
complete commit 293
complete commit 294
complete commit 295
complete commit 296
complete commit 297
complete commit 298
complete commit 299
complete commit 300
complete commit 301
complete commit 302
complete commit 303
complete commit 304
complete commit 305
complete commit 306
complete commit 307
complete commit 308
complete commit 309
complete commit 310
complete commit 311
complete commit 312
complete commit 313
complete commit 314
complete commit 315
complete commit 316
complete commit 317
complete commit 318
complete commit 319
complete commit 320
complete commit 321
complete commit 322
complete commit 323
complete commit 324
complete commit 325
complete commit 326
complete commit 327
complete commit 328
complete commit 329
complete commit 330
complete commit 331
complete commit 332
complete commit 333
complete commit 334
complete commit 335
complete commit 336
complete commit 337
complete commit 338
complete commit 339
complete commit 340
complete commit 341
complete commit 342
complete commit 343
complete commit 344
complete commit 345
complete commit 346
complete commit 347
complete commit 348
complete commit 349
complete commit 350
complete commit 351
complete commit 352
complete commit 353
complete commit 354
complete commit 355
complete commit 356
complete commit 357
complete commit 358
complete commit 359
complete commit 360
complete commit 361
complete commit 362
complete commit 363
complete commit 364
complete commit 365
complete commit 366
complete commit 367
complete commit 368
complete commit 369
complete commit 370
complete commit 371
complete commit 372
complete commit 373
complete commit 374
complete commit 375
complete commit 376
complete commit 377
complete commit 378
complete commit 379
complete commit 380
complete commit 381
complete commit 382
complete commit 383
complete commit 384
complete commit 385
complete commit 386
complete commit 387
complete commit 388
complete commit 389
complete commit 390
complete commit 391
complete commit 392
complete commit 393
complete commit 394
complete commit 395
complete commit 396
complete commit 397
complete commit 398
complete commit 399
complete commit 400
complete commit 401
complete commit 402
complete commit 403
complete commit 404
complete commit 405
complete commit 406
complete commit 407
complete commit 408
complete commit 409
complete commit 410
complete commit 411
complete commit 412
complete commit 413
complete commit 414
complete commit 415
complete commit 416
complete commit 417
complete commit 418
complete commit 419
complete commit 420
complete commit 421
complete commit 422
complete commit 423
complete commit 424
complete commit 425
complete commit 426
complete commit 427
complete commit 428
complete commit 429
complete commit 430
complete commit 431
complete commit 432
complete commit 433
complete commit 434
complete commit 435
complete commit 436
complete commit 437
complete commit 438
complete commit 439
complete commit 440
complete commit 441
complete commit 442
complete commit 443
complete commit 444
complete commit 445
complete commit 446
complete commit 447
complete commit 448
complete commit 449
complete commit 450
complete commit 451
complete commit 452
complete commit 453
complete commit 454
complete commit 455
complete commit 456
complete commit 457
complete commit 458
complete commit 459
complete commit 460
complete commit 461
complete commit 462
complete commit 463
complete commit 464
complete commit 465
complete commit 466
complete commit 467
complete commit 468
complete commit 469
complete commit 470
complete commit 471
complete commit 472
complete commit 473
complete commit 474
complete commit 475
complete commit 476
complete commit 477
complete commit 478
complete commit 479
complete commit 480
complete commit 481
complete commit 482
complete commit 483
complete commit 484
complete commit 485
complete commit 486
complete commit 487
complete commit 488
complete commit 489
complete commit 490
complete commit 491
complete commit 492
complete commit 493
complete commit 494
complete commit 495
complete commit 496
complete commit 497
complete commit 498
complete commit 499
complete commit 500
complete commit 501
complete commit 502
complete commit 503
complete commit 504
complete commit 505
complete commit 506
complete commit 507
complete commit 508
complete commit 509
complete commit 510
complete commit 511
complete commit 512
complete commit 513
complete commit 514
complete commit 515
complete commit 516
complete commit 517
complete commit 518
complete commit 519
complete commit 520
complete commit 521
complete commit 522
complete commit 523
complete commit 524
complete commit 525
complete commit 526
complete commit 527
complete commit 528
complete commit 529
complete commit 530
complete commit 531
complete commit 532
complete commit 533
complete commit 534
complete commit 535
complete commit 536
complete commit 537
complete commit 538
complete commit 539
complete commit 540
complete commit 541
complete commit 542
complete commit 543
complete commit 544
complete commit 545
complete commit 546
complete commit 547
complete commit 548
complete commit 549
complete commit 550
complete commit 551
complete commit 552
complete commit 553
complete commit 554
complete commit 555
complete commit 556
complete commit 557
complete commit 558
complete commit 559
complete commit 560
complete commit 561
complete commit 562
complete commit 563
complete commit 564
complete commit 565
complete commit 566
complete commit 567
complete commit 568
complete commit 569
complete commit 570
complete commit 571
complete commit 572
complete commit 573
complete commit 574
complete commit 575
complete commit 576
complete commit 577
complete commit 578
complete commit 579
complete commit 580
complete commit 581
complete commit 582
complete commit 583
complete commit 584
complete commit 585
complete commit 586
complete commit 587
complete commit 588
complete commit 589
complete commit 590
complete commit 591
complete commit 592
complete commit 593
complete commit 594
complete commit 595
complete commit 596
complete commit 597
complete commit 598
complete commit 599
complete commit 600
complete commit 601
complete commit 602
complete commit 603
complete commit 604
complete commit 605
complete commit 606
complete commit 607
complete commit 608
complete commit 609
complete commit 610
complete commit 611
complete commit 612
complete commit 613
complete commit 614
complete commit 615
complete commit 616
complete commit 617
complete commit 618
complete commit 619
complete commit 620

/tmp/ipykernel_3893/3112454515.py:65: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[4] == "Snow / Slush / Ice": pavement = 2

complete commit 621
complete commit 622
complete commit 623
complete commit 624
complete commit 625
complete commit 626
complete commit 627
complete commit 628
complete commit 629
complete commit 630
complete commit 631
complete commit 632
complete commit 633
complete commit 634
complete commit 635
complete commit 636
complete commit 637
complete commit 638
complete commit 639
complete commit 640
complete commit 641
complete commit 642
complete commit 643
complete commit 644
complete commit 645
complete commit 646
complete commit 647
complete commit 648
complete commit 649
complete commit 650
complete commit 651
complete commit 652
complete commit 653
complete commit 654
complete commit 655
complete commit 656
complete commit 657
complete commit 658
complete commit 659
complete commit 660
complete commit 661
complete commit 662
complete commit 663
complete commit 664
complete commit 665
complete commit 666
complete commit 667
complete commit 668
complete commit 669
complete commit 670
complete commit 671
complete commit 672
complete commit 673
complete commit 674
complete commit 675
complete commit 676
complete commit 677
complete commit 678
complete commit 679
complete commit 680
complete commit 681
complete commit 682
complete commit 683
complete commit 684
complete commit 685
complete commit 686
complete commit 687
complete commit 688
complete commit 689
complete commit 690
complete commit 691

In [74]:
df_adas.head(5)

,Brand,Accident date,City,Road,Pavement,Movement,Weather,Speed
0,Honda (American Honda Motor Co.),NOV-2024,LOUISVILLE,Street,Dry,Proceeding Straight,Clear,97
2,"Nissan North America, Inc.",OCT-2024,Irving,Highway / Freeway,Unknown,Unknown,Other,42
3,"Subaru of America, Inc.",NOV-2024,Plainview,Rural Road,Dry,Proceeding Straight,Clear,126
5,"Tesla, Inc.",NOV-2024,Worcester,Unknown,Unknown,Unknown,Other,48
6,"Tesla, Inc.",NOV-2024,Bothell,Unknown,Unknown,Unknown,Other,19

In [102]:
import mysql.connector

cnt = 1
dic = {"JAN":"01", "FEB":"02", "MAR":"03", "APR":"04", "MAY":"05", "JUN":"06", "JUL":"07", "AUG":"08", "SEP":"09", "OCT":"10", "NOV":"11", "DEC":"12"}

remote = mysql.connector.connect(
    host = "database-eda.chuw4mu887pw.ap-northeast-2.rds.amazonaws.com",
    user = "root",
    password = "myung234",
    database = "eda"
)

cursor = remote.cursor(buffered = True)

#sql = "insert into car_accident values(%s, %s, %s, %s, %s)"
sql = """
INSERT INTO car_accident (
    accident_date, alcohol, speed, age, sex, auto_id, state_id, 
    weather_id, road_id, movement_id, brand_id, pavement_id
) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

for i, row in df_adas.iterrows():
    # SF
    if row[2] != "San Francisco": continue

    # brand
    if row[0] == "Tesla, Inc.": brand = 1
    elif row[0] == "Cruise LLC": brand = 2
    else: continue

    # speed
    speed = row[7] 

    # weather
    if row[6] == "Clear": weather = 0
    elif row[6] == "Cloudy": weather = 1
    elif row[6] == "Rain": weather = 2
    elif row[6] == "Snow": weather = 3
    elif row[6] == "Other": weather = 4

    # road
    if row[3] == "Street" or row[3] == "Rural Road" or row[3] == "Unpaved Road": road = 0
    elif row[3] == "Highway / Freeway": road = 1
    elif row[3] == "Intersection" or row[3] == "Traffic Circle": road = 2
    elif row[3] == "Parking Lot": road = 3
    else: continue

    # movement
    if row[5] == "Crossing into Opposing Lane": movement = 0
    elif row[5] == "Changing Lanes" or row[5] == "Lane / Road Departure" or row[5] == "Traveling Wrong Way": movement = 1
    elif row[5] == "Proceeding Straight": movement = 2
    elif row[5] == "Making Left Turn" or row[5] == "Making Right Turn": movement = 3
    elif row[5] == "Parking Maneuver": movement = 5
    else: movement = 8

    # pavement
    if row[4] == "Dry": pavement = 0
    elif row[4] == "Wet": pavement = 1
    elif row[4] == "Snow / Slush / Ice": pavement = 2
    else: pavement = 3
        
    # date    
    date = ""
    date += row[1][-4:]
    date += dic[row[1][:3]]
    date += "01"

    tmp = (date, None, speed, None, None, 0, 1, weather, road, movement, brand, pavement)
    
    cursor.execute(sql, tmp)
    remote.commit()
    print("complete commit", str(cnt))
    cnt += 1

remote.close()

/tmp/ipykernel_3893/3430953326.py:25: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if row[2] != "San Francisco": continue
/tmp/ipykernel_3893/3430953326.py:28: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if row[0] == "Tesla, Inc.": brand = 1
/tmp/ipykernel_3893/3430953326.py:33: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  speed = row[7]
/tmp/ipykernel_3893/3430953326.py:36: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if row[6] == "Clear": weather = 0
/tmp/ipykernel_3893/3430953326.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[6] == "Cloudy": weather = 1
/tmp/ipykernel_3893/3430953326.py:38: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[6] == "Rain": weather = 2
/tmp/ipykernel_3893/3430953326.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[6] == "Snow": weather = 3
/tmp/ipykernel_3893/3430953326.py:40: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[6] == "Other": weather = 4
/tmp/ipykernel_3893/3430953326.py:43: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if row[3] == "Street" or row[3] == "Rural Road" or row[3] == "Unpaved Road": road = 0
/tmp/ipykernel_3893/3430953326.py:44: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[3] == "Highway / Freeway": road = 1
/tmp/ipykernel_3893/3430953326.py:50: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if row[5] == "Crossing into Opposing Lane": movement = 0
/tmp/ipykernel_3893/3430953326.py:51: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[5] == "Changing Lanes" or row[5] == "Lane / Road Departure" or row[5] == "Traveling Wrong Way": movement = 1
/tmp/ipykernel_3893/3430953326.py:52: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[5] == "Proceeding Straight": movement = 2
/tmp/ipykernel_3893/3430953326.py:53: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[5] == "Making Left Turn" or row[5] == "Making Right Turn": movement = 3
/tmp/ipykernel_3893/3430953326.py:54: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[5] == "Parking Maneuver": movement = 5
/tmp/ipykernel_3893/3430953326.py:58: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if row[4] == "Dry": pavement = 0
/tmp/ipykernel_3893/3430953326.py:59: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[4] == "Wet": pavement = 1
/tmp/ipykernel_3893/3430953326.py:60: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[4] == "Snow / Slush / Ice": pavement = 2
/tmp/ipykernel_3893/3430953326.py:65: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  date += row[1][-4:]
/tmp/ipykernel_3893/3430953326.py:66: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  date += dic[row[1][:3]]
/tmp/ipykernel_3893/3430953326.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[3] == "Intersection" or row[3] == "Traffic Circle": road = 2
/tmp/ipykernel_3893/3430953326.py:46: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif row[3] == "Parking Lot": road = 3

complete commit 1
complete commit 2
complete commit 3
complete commit 4
complete commit 5
complete commit 6
complete commit 7
complete commit 8
complete commit 9
complete commit 10
complete commit 11

In [93]:
df_adas.head(5)

,Brand,Accident date,City,Road,Pavement,Movement,Weather,Speed
0,Honda (American Honda Motor Co.),NOV-2024,LOUISVILLE,Street,Dry,Proceeding Straight,Clear,97
2,"Nissan North America, Inc.",OCT-2024,Irving,Highway / Freeway,Unknown,Unknown,Other,42
3,"Subaru of America, Inc.",NOV-2024,Plainview,Rural Road,Dry,Proceeding Straight,Clear,126
5,"Tesla, Inc.",NOV-2024,Worcester,Unknown,Unknown,Unknown,Other,48
6,"Tesla, Inc.",NOV-2024,Bothell,Unknown,Unknown,Unknown,Other,19